import Link from "next/link";
import { ArrowLeft, ArrowUpRight, Bot, Database, MonitorCheck } from "lucide-react";

export const metadata = { title: "기술 노트 | 김지현 Portfolio", description: "김지현의 프로젝트 설계, 데이터 자동화, 모델 실험과 배포 검증 기록입니다." };

const notes = [
  { icon: Database, category: "PRODUCT DATA PIPELINE", title: "외부 전시 API를 정적 스냅샷으로 바꾼 이유", summary: "Pote의 전시 카탈로그는 문화공공데이터광장 정보를 사용한다. Vercel 환경에서 외부 API 응답이 안정적이지 않은 제약을 확인한 뒤, GitHub Actions가 매일 데이터를 수집·정제해 정적 JSON을 갱신하는 방식으로 바꿨다.", takeaways: ["실시간 호출보다 배포 환경에서의 안정성을 먼저 검증했다.", "외부 데이터는 수집·정제·표시 단계를 분리해 장애 범위를 줄였다.", "사용자 화면은 외부 API 호출 없이 빠르게 전시 카탈로그를 제공한다."], href: "/projects/pote-gallery/process", action: "Pote 제작 과정 보기" },
  { icon: Bot, category: "MACHINE LEARNING EXPERIMENT", title: "모델 하나를 고르기 전, 비교 기준을 먼저 세우기", summary: "난임 임신 성공 예측 팀 프로젝트에서 CatBoost와 LightGBM 등 여러 모델을 반복 실험하며 성능을 비교했다. 단일 결과만 보는 대신, 팀이 같은 기준으로 판단할 수 있도록 실험 결과와 개선 방향을 공유하는 데 집중했다.", takeaways: ["모델 선택은 한 번의 점수보다 비교 가능한 실험 흐름이 중요하다.", "성능 변화의 이유를 설명할 수 있어야 다음 실험을 설계할 수 있다.", "협업에서는 결과와 판단 근거를 함께 남겨야 의사결정이 흔들리지 않는다."], href: "/projects/infertility-pregnancy-prediction", action: "난임 예측 사례 보기" },
  { icon: MonitorCheck, category: "RELEASE QUALITY", title: "기능 구현 뒤에 실제 브라우저 검증을 남기는 이유", summary: "Pote는 작품 탐색, 찜, 문의, 실제 공간 미리보기처럼 화면에서 직접 확인해야 하는 기능이 많다. 데스크톱과 모바일에서 실제 흐름을 점검하고, 배포 뒤에도 주요 화면을 다시 확인하는 방식을 유지했다.", takeaways: ["코드가 통과해도 사용자 화면의 문제까지 보장하지는 않는다.", "반응형 화면은 기능별 핵심 행동을 기준으로 확인한다.", "배포 검증은 구현의 마지막 단계가 아니라 서비스 품질을 지키는 과정이다."], href: "/projects/pote-gallery", action: "Pote 프로젝트 보기" }
];

export default function NotesPage() {
  return <main className="min-h-screen bg-[#15171B] text-[#F5F1E8]"><header className="border-b border-white/10 bg-[#15171B]"><div className="mx-auto flex min-h-16 max-w-[1120px] items-center justify-between px-5 sm:px-8"><Link href="/" className="inline-flex items-center gap-2 text-sm font-bold text-[#B8BDC7] transition hover:text-[#B9E4D0]"><ArrowLeft className="h-4 w-4" /> 포트폴리오</Link><span className="text-xs font-black tracking-[0.14em] text-[#B9E4D0]">TECHNICAL NOTES</span></div></header><section className="border-b border-white/10"><div className="mx-auto max-w-[1120px] px-5 py-16 sm:px-8 sm:py-24"><p className="text-sm font-black text-[#B9E4D0]">기술 노트</p><h1 className="mt-5 max-w-3xl text-4xl font-black leading-tight sm:text-6xl">만든 것에서<br /><span className="text-[#C9BDF4]">배운 판단을 기록합니다.</span></h1><p className="mt-7 max-w-2xl text-base leading-8 text-[#B8BDC7] sm:text-lg">프로젝트 결과를 나열하는 대신, 문제를 어떻게 나누고 어떤 제약 안에서 선택했는지 정리합니다.</p></div></section><section className="mx-auto max-w-[1120px] px-5 py-12 sm:px-8 sm:py-16"><div className="grid gap-5">{notes.map(({ icon: Icon, category, title, summary, takeaways, href, action }) => <article key={title} className="rounded-md border border-white/10 bg-[#202329] p-6 sm:p-8"><Icon className="h-6 w-6 text-[#F0A58D]" aria-hidden="true" /><p className="mt-5 text-xs font-black tracking-[0.12em] text-[#B9E4D0]">{category}</p><h2 className="mt-3 text-2xl font-black leading-snug sm:text-3xl">{title}</h2><p className="mt-4 max-w-3xl text-sm leading-7 text-[#C4C9D2]">{summary}</p><ul className="mt-6 grid gap-2 text-sm leading-6 text-[#D8DCE3]">{takeaways.map((item) => <li key={item} className="flex gap-2"><span className="text-[#F0A58D]">•</span><span>{item}</span></li>)}</ul><Link href={href} className="mt-7 inline-flex items-center gap-2 text-sm font-black text-[#B9E4D0] transition hover:text-white">{action}<ArrowUpRight className="h-4 w-4" /></Link></article>)}</div></section></main>;
}
